openapi: 3.1.1
info:
  title: Rimac Appointments API
  version: 1.0.0
paths:
  /appointments:
    post:
      summary: Crear agendamiento
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAppointmentRequest'
      responses:
        '202':
          description: Aceptado
  /appointments/{insuredId}:
    get:
      summary: Listar por insuredId
      parameters:
        - name: insuredId
          in: path
          required: true
          schema: { type: string, pattern: '^[0-9]{5}$' }
      responses:
        '200':
          description: OK
components:
  schemas:
    CreateAppointmentRequest:
      type: object
      required: [ insuredId, scheduleId, countryISO ]
      properties:
        insuredId: { type: string, pattern: '^[0-9]{5}$' }
        scheduleId: { type: integer }
        countryISO: { type: string, enum: [PE, CL] }
